/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-07-23 04:44:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jjam_005f6_005fmypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1563774131512L));
    _jspx_dependants.put("/WEB-INF/views/chatbot.jsp", Long.valueOf(1563523068134L));
    _jspx_dependants.put("/WEB-INF/views/recentList.jsp", Long.valueOf(1563849753720L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Shop Homepage - Start Bootstrap Template</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<style>\r\n");
      out.write("\t#header{\r\n");
      out.write("\tmargin-top : -130px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/style/mypage1.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/style/main.css\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet prepatch\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel='stylesheet prefetch' -->\r\n");
      out.write("<!-- \thref='//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'> -->\r\n");
      out.write("<!-- <link rel='stylesheet prefetch' -->\r\n");
      out.write("<!-- \thref='//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css'> -->\r\n");
      out.write("<!-- <link rel='stylesheet prefetch' -->\r\n");
      out.write("<!-- \thref='//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css'> -->\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("//마이페이지 입장하자마자 바로 개인정보변경 뜨게하기\r\n");
      out.write("  $(function(){\r\n");
      out.write("\t  $(\".mypage-menu a\").eq(0).css(\"background-color\", \"#147b6b\");\r\n");
      out.write("\t  $(\".mypage-menu a\").eq(0).css(\"color\", \"white\");\r\n");
      out.write("\t  $.ajax({\r\n");
      out.write("\t\t  type:\"POST\",\r\n");
      out.write("\t\t  url: \"jjam_6_mypage_privacy.do\",\r\n");
      out.write("\t\t  success:function(data){\r\n");
      out.write("\t\t\t  $(\"#ddd\").html(data);\r\n");
      out.write("\t\t  }, error: function(){\r\n");
      out.write("\t\t\t  alert(\"에러발생\");\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  });\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t//마이페이지안에 탭 누를때 발생되는 ajax\r\n");
      out.write("// \t  $(\".mypage-menu a\").eq(1).trigger(\"click\");\r\n");
      out.write("      $('.mypage-menu a').each(function(){\r\n");
      out.write("          $(this).click(function() { \r\n");
      out.write("        \t  $('.mypage-menu a').css(\"background-color\", \"white\");\r\n");
      out.write("        \t  $('.mypage-menu a').css(\"color\", \"black\");\r\n");
      out.write("        \t  $(this).css(\"background-color\", \"#147b6b\");\r\n");
      out.write("        \t  $(this).css(\"color\", \"white\");\r\n");
      out.write("        \t activeTab = $(this).attr(\"rel\");\r\n");
      out.write("        \t $(\"#ddd\").empty();\r\n");
      out.write("          $.ajax({\r\n");
      out.write("        \t  type:'POST',\r\n");
      out.write("        \t  url:activeTab+'.do',\r\n");
      out.write("        \t  data:\r\n");
      out.write("        \t\t  {\"bc_id\" : $(\"#userName\").text()},\r\n");
      out.write("        \t  success:function(data){\r\n");
      out.write("        \t\t  $('#ddd').html(data);\r\n");
      out.write("        \t  },\r\n");
      out.write("        \t  error:function(){\r\n");
      out.write("        \t\t  alert(\"통신실패\");\r\n");
      out.write("        \t  }\r\n");
      out.write("          });\r\n");
      out.write("          });\r\n");
      out.write("      });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//주소 스크립트\r\n");
      out.write("\r\n");
      out.write("\t function sample4_execDaumPostcode() {\r\n");
      out.write("\t        new daum.Postcode({\r\n");
      out.write("\t            oncomplete: function(data) {\r\n");
      out.write("\t                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("\t                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t                var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t                var extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("\t                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("\t                    extraRoadAddr += data.bname;\r\n");
      out.write("\t                }\r\n");
      out.write("\t                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("\t                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("\t                }\r\n");
      out.write("\t                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t                if(extraRoadAddr !== ''){\r\n");
      out.write("\t                    extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t                }\r\n");
      out.write("\r\n");
      out.write("\t                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t                document.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("\t                document.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("\t                document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("\t                \r\n");
      out.write("\t                // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\r\n");
      out.write("\t                if(roadAddr !== ''){\r\n");
      out.write("\t                    document.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\r\n");
      out.write("\t                } else {\r\n");
      out.write("\t                    document.getElementById(\"sample4_extraAddress\").value = '';\r\n");
      out.write("\t                }\r\n");
      out.write("\r\n");
      out.write("\t                var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("\t                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("\t                if(data.autoRoadAddress) {\r\n");
      out.write("\t                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("\t                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("\t                    guideTextBox.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("\t                } else if(data.autoJibunAddress) {\r\n");
      out.write("\t                    var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("\t                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("\t                    guideTextBox.style.display = 'block';\r\n");
      out.write("\t                } else {\r\n");
      out.write("\t                    guideTextBox.innerHTML = '';\r\n");
      out.write("\t                    guideTextBox.style.display = 'none';\r\n");
      out.write("\t                }\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }).open();\r\n");
      out.write("\t    }\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ---------------------------------상단 고정 메뉴바--------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("   <h1 class=\"seperator\"></h1>\r\n");
      out.write("     <nav id=\"top_navcolor\" class=\"navbar fixed-top navbar navbar-expand-xl navbar-dark\">\r\n");
      out.write("         <!-- fixed-top 상단고정-->\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("             <!-- 브랜드 로고 삽입-->\r\n");
      out.write("             <a href=\"jjam_3_form.jsp\" class=\"navbar-brand\">\r\n");
      out.write("                 <img id=\"logo\" class=\"\" style=\"width: 60px; height: 60px;\" src=\"./resources/image/character.png\" alt=\"\"><img src=\"./resources/image/JJCR_white1.png\">\r\n");
      out.write("             </a>\r\n");
      out.write("             <!-- 햄버거 버튼-->\r\n");
      out.write("             <button class=\"navbar-toggler ham\" data-toggle=\"collapse\" data-target=\"#myNav\">\r\n");
      out.write("                 <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("             </button>\r\n");
      out.write("             <!-- 네비게이션 버튼 -->\r\n");
      out.write("             <div id=\"myNav\" class=\"collapse navbar-collapse justify-content-end\">\r\n");
      out.write("                 <ul class=\"navbar-nav\">\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">HOME</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_3_form.do\" class=\"nav-link\">나눔찾기(메인지도)</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_2_search.do\" class=\"nav-link\">검색하기</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_6_mypage.do\" class=\"nav-link\">마이페이지</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_login&out.do\" class=\"nav-link\">로그인/로그아웃</a>\r\n");
      out.write("                    \r\n");
      out.write("                     </li>\r\n");
      out.write("                 </ul>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </nav>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--------------------------------------본문 ------------------------------------------------------>\r\n");
      out.write("\t<span style=\"position:fixed; absolute; left:88%; top:260px;\">");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"width:160px; height:495px; border: 1px solid #E2E2E2;\">\r\n");
      out.write("\t\t<div style=\"display: grid; grid-template-columns: 100%; grid-template-rows: 30px 100px 30px 100px 30px 100px 30px160px 30px;\">\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center;\"><STRONG>RECENT VIEW</STRONG></div>\r\n");
      out.write("\t\t\t\t<div style=\" text-align:center; background-color:#E2E2E2; margin:3px;\"><img src=\"./resources/image/category_icon/bread_icon.png\"></div>\r\n");
      out.write("\t\t\t\t<div style=\" text-align:center;\"><input type=\"text\" value=\"빵\" style=\"border:none; text-align:center; width:147px;\" readonly></div>\r\n");
      out.write("\t\t\t\t<div style=\" text-align:center; background:#E2E2E2; margin:3px;\"><img src=\"./resources/image/category_icon/bread_icon.png\"></div>\r\n");
      out.write("\t\t\t\t<div style=\" text-align:center;\"><input type=\"text\" value=\"빵\" style=\"border:none; text-align:center; width:147px;\" readonly></div>\r\n");
      out.write("\t\t\t\t<div style=\" text-align:center; background:#E2E2E2; margin:3px;\"><img src=\"./resources/image/category_icon/bread_icon.png\"></div>\r\n");
      out.write("\t\t\t\t<div style=\" text-align:center;\"><input type=\"text\" value=\"빵\" style=\"border:none; text-align:center; width:147px;\" readonly></div>\r\n");
      out.write("\t\t\t\t<div style=\"text-align:center;\"></br><img src=\"./resources/image/BI-jjam.png\" style=\"width: 90px; height: 90px\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center; margin-top:10px;\">식자재 나눔 웹서비스</br>짬처리</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("\t<!-- Page Content -->\r\n");
      out.write("\t<div class=\"mypage\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div></div>\r\n");
      out.write("\t\t<!-- 공백 -->\r\n");
      out.write("\t\t<div class=\"\">\r\n");
      out.write("\t\t\t<img width=\"100%\" src=\"./resources/image/mypage_test1.png\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 공백 -->\r\n");
      out.write("\t\t<div></div>\r\n");
      out.write("\t\t<!-- 공백 -->\r\n");
      out.write("\t\t<!-- ------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t<div class=\" mypage-columns \">\r\n");
      out.write("\t\t\t<!-- ----------------------------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t<!-- ------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mypage-rows \">\r\n");
      out.write("\t\t\t\t\t<div style=\"padding:20px;\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./resources/image/3.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 200px; height: 200px; border-radius: 100px;\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"My Image\"></br></br>\r\n");
      out.write("\t\t\t\t\t\t<h5 style=\"color:black;\"><span id=\"userName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>님 안녕하세요</h5></br></br></br>\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"my-4\" style=\"color:black;\">마이페이지</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- ------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t\t<div class=\"mypage-menu\">\r\n");
      out.write("\t\t\t\t\t<div><a class=\"list-group-item\" rel=\"jjam_6_mypage_privacy\">개인정보변경</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div><a class=\"list-group-item\" rel=\"jjam_6_mypage_letter\">댓글 및 쪽지</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div><a class=\"list-group-item\" rel=\"jjam_6_mypage_jjim\">찜목록</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div><a class=\"list-group-item\" rel=\"jjam_6_mypage_payment\">결제내역</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ------------------------------------------------------------------------- -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<!-- ------------------------------------------------------------------------- -->\r\n");
      out.write("\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t<div id=\"ddd\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t\r\n");
      out.write("\t<footer class=\"py-5 bg-dark footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<p class=\"m-0 text-center text-white\">Copyright &copy; Your\r\n");
      out.write("\t\t\t\tWebsite 2019</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!----------------------------------쪽지 modal 창----------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal\" tabindex=\"-1\" id=\"comment\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: grid; grid-template-columns: 30% 40% 30%;\">\r\n");
      out.write("\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-title\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./resources/image/letter.png\" width=\"100px\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<p>양파좀 네고해주세요</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-secondary\">\r\n");
      out.write("\t\t\t\t\t\t<small>님 양파 네고좀</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">확인</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--------------------------------  챗봇 api------------------- -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"frogue-container\" class=\"position-right-bottom\" data-chatbot=\"00b6f39a-b84c-48d4-9037-e20bfac8625a\" data-user=\"사용자ID\" data-init-key=\"value\"></div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        (function(d, s, id){\r\n");
      out.write("            var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("            if (d.getElementById(id)) {return;}\r\n");
      out.write("            js = d.createElement(s); js.id = id;\r\n");
      out.write("            js.src = \"https:\\/\\/danbee.ai/js/plugins/frogue-embed/frogue-embed.min.js\";\r\n");
      out.write("            fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("        }(document, 'script', 'frogue-embed'));\r\n");
      out.write("        </script> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"jjoin\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <div class=\"footer fixed-bottom\">copylight</div> -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap core JavaScript -->\r\n");
      out.write("<!-- \t<script src=\"./resources/image/vendor/jquery/jquery.min.js\"></script> -->\r\n");
      out.write("<!-- \t<script -->\r\n");
      out.write("<!-- \t\tsrc=\"./resources/image/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
