/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-07-18 09:10:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.java.jjam.domain.BoardAndCateVO;

public final class jjam_005f3_005fmodal_005fjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/programming/jjam/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/jjam/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562204675346L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.java.jjam.domain.BoardAndCateVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script> -->\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t//참여하기 클릭했을때 결제페이지에 정보 넘기기 \r\n");
      out.write("\t$('.participation').click(function(){\r\n");
      out.write("\t\t$(\".parti\").empty();\r\n");
      out.write(" \t\tvar c_id = $(\"#c_id2\").text();\r\n");
      out.write(" \t\tvar cate_name = $(\"#cate_name2\").text();\r\n");
      out.write(" \t\tvar b_title = $(\"#b_title2\").text();\r\n");
      out.write(" \t\tvar b_location = $(\"#b_location2\").text();\r\n");
      out.write(" \t\tvar b_date = $(\"#b_date2\").text();\r\n");
      out.write(" \t\tvar b_content = $(\"#b_content2\").text();\r\n");
      out.write(" \t\tvar b_price = $(\"#b_price2\").text();\r\n");
      out.write(" \t\tvar b_no = $(\"#b_no2\").text();\r\n");
      out.write(" \t\tvar bc_id = $(\"#bc_id2\").text();  //입력한 구매자id값 \r\n");
      out.write(" \t\r\n");
      out.write("//  \t\tvar cate_image = $(\"#cate_image\").attr(\"src\");\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t$(\"#c_id1\").text(c_id);\r\n");
      out.write(" \t\t$(\"#cate_name1\").text(cate_name);\r\n");
      out.write(" \t\t$(\"#b_title1\").text(b_title);\r\n");
      out.write(" \t\t$(\"#b_location1\").text(b_location);\r\n");
      out.write(" \t\t$(\"#b_date1\").text(b_date);\r\n");
      out.write(" \t\t$(\"#b_price1\").text(b_price);\r\n");
      out.write(" \t\t$(\"#b_content1\").text(b_content);\r\n");
      out.write(" \t\t$(\"#b_no1\").text(b_no);\r\n");
      out.write(" \t\t$(\"#bc_id1\").text(bc_id);  //구매자 id값 추후 삭제 안보이게 처리\r\n");
      out.write("\t});\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//////////////////찜하기\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".jjim\").click(function(){\r\n");
      out.write("\t\talert(\"클릭\");\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\turl:\"jjam_3_jjim.do\",\r\n");
      out.write("\t\t\tdata:\r\n");
      out.write("\t\t\t{\"b_no\":$(\"#b_no2\").text(),\r\n");
      out.write("\t\t\t \"c_id\" : $(\"#bc_id1\").text()        \t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(){\r\n");
      out.write("\t\t\t\talert(\"찜 성공\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(){\r\n");
      out.write("\t\t\t\talert(\"찜 실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" \t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 BoardAndCateVO data = (BoardAndCateVO)request.getAttribute("data"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"join\" class=\"modal fade\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content modal-size\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h4>나눔에 참여하기 </h4>\r\n");
      out.write("                         \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body \">\r\n");
      out.write("                            <div class=\"modal-inner-grid\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                            <li><span id=\"c_id2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.c_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> 님의 나눔</li>\r\n");
      out.write("                                            <li>글번호&nbsp; : <span id=\"b_no2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("                                            <!-- 추후에 안보이게 처리 -->\r\n");
      out.write("                                            <li>구매자id&nbsp; : <span id=\"bc_id2\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("                                            <li>제목 &nbsp; : <span id=\"b_title2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.b_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("                                            <li>품목 &nbsp; : <span id=\"cate_name2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.cate_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("                                            <li>위치 &nbsp; : <span id=\"b_location2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.b_location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("                                            <li>가격 &nbsp; : <span id=\"b_price2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.b_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("                                            <li>날짜 &nbsp; : <span id=\"b_date2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.b_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("                                             <li>내용 &nbsp; : <span id=\"b_content2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.b_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("                                             <span id=\"b_no2\" style=\"display:none;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                                             \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-12\"\r\n");
      out.write("                                        style=\"display: grid; grid-template-columns:50% 50%; grid-template-rows:50% 50%;\">\r\n");
      out.write("                                        <input type=\"button\" class=\"col-sm-12 participation\"\r\n");
      out.write("                                            style=\"color:white; background-color: #147b6b\" value=\"참여하기\" data-toggle=\"modal\" data-target=\"#pay\">\r\n");
      out.write("                                        <input type=\"button\" class=\"col-sm-12 jjim\"\r\n");
      out.write("                                            style=\"color:white; background-color: #f37f7f\" value=\"찜 하기\">\r\n");
      out.write("                                        <input type=\"button\" class=\"col-sm-12 cancel\"  data-dismiss=\"modal\"\r\n");
      out.write("                                            style=\"color:white; background-color: #999999\" value=\"취소\">\r\n");
      out.write("                                        <input type=\"button\" class=\"col-sm-12\"\r\n");
      out.write("                                            style=\"color:white; background-color: #558ccf\" value=\"길찾기\"\r\n");
      out.write("                                            data-toggle=\"modal\" data-target=\"#road\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div><img src=\"");
      out.print(data.getCate_icon());
      out.write(".png\" class=\"w-100 h-100 cate_image\" alt=\"\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
