/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-07-22 05:44:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jjam_005f3_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1563774131512L));
    _jspx_dependants.put("jar:file:/C:/programming/jjam/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/jjam/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562204675346L));
    _jspx_dependants.put("/WEB-INF/views/chatbot.jsp", Long.valueOf(1563523068134L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<!--     <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" -->\r\n");
      out.write("<!--         integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" -->\r\n");
      out.write("<!--         crossorigin=\"anonymous\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- https://getbootstrap.com/docs/4.3/getting-started/introduction/ 부트스트랩에서 가져옴-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=313dc2a3dad52079f42012b67c645f76&libraries=services\"></script>\r\n");
      out.write("   <style>\r\n");
      out.write("    .wrap {position: absolute;left:112px;bottom: -30px;width: 220px;height: 100px;margin-left: -144px;text-align: left;overflow: hidden;font-size: 12px;font-family: 'Malgun Gothic', dotum, '돋움', sans-serif;line-height: 1.5;}\r\n");
      out.write("    .wrap * {padding: 0;margin: 0;}\r\n");
      out.write("    .wrap .info {width: 286px;height: 120px;border-radius: 5px;border-bottom: 2px solid #ccc;border-right: 1px solid #ccc;overflow: hidden;background: #fff;}\r\n");
      out.write("    .wrap .info:nth-child(1) {border: 0;box-shadow: 0px 1px 2px #888;}\r\n");
      out.write("    .info .title {padding: 5px 0 0 10px;height: 30px;background: #eee;border-bottom: 1px solid #ddd;font-size: 18px;font-weight: bold;}\r\n");
      out.write("    .info .close {position: absolute;top: 10px;right: 10px;color: #888;width: 17px;height: 17px;background: url('http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/overlay_close.png');}\r\n");
      out.write("    .info .close:hover {cursor: pointer;}\r\n");
      out.write("    .info .body {position: relative;overflow: hidden;}\r\n");
      out.write("    .info .desc {position: relative;margin: 13px 0 0 90px;height: 75px;}\r\n");
      out.write("    .desc .ellipsis {overflow: hidden;text-overflow: ellipsis;white-space: nowrap;}\r\n");
      out.write("    .desc .jibun {font-size: 11px;color: #888;margin-top: -2px;}\r\n");
      out.write("    .info .img {position: absolute;top: 6px;left: 5px;width: 73px;height: 71px;border: 1px solid #ddd;color: #888;overflow: hidden;}\r\n");
      out.write("    .info:after {content: '';position: absolute;margin-left: -12px;left: 50%;bottom: 0;width: 22px;height: 12px;background: url('http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/vertex_white.png')}\r\n");
      out.write("    .info .link {color: #5085BB;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/style/main.css\" >\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/825d367943.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("  //controller에서 가져온 jsonArray를 파싱\r\n");
      out.write("    var jsonList = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jsonList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t$(function(){\r\n");
      out.write("   \t $('#info').modal('show');// 페이지 진입시 레이어팝업 modal#info 실행\r\n");
      out.write("\r\n");
      out.write("   \t\r\n");
      out.write("   \t \r\n");
      out.write("   \t \r\n");
      out.write("   //map 관련 jquery문\r\n");
      out.write("     $(\".create\").click(function(){\r\n");
      out.write(" \t\tvar address = $(\".address\").text();\r\n");
      out.write(" \t\tvar latitude = $(\".latitude\").text();\r\n");
      out.write(" \t\tvar longitude = $(\".longitude\").text();\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t$(\"#location\").prop('value',address);\r\n");
      out.write(" \t\t$(\"#latitude\").prop('value', latitude);\r\n");
      out.write(" \t\t$(\"#longitude\").prop('value', longitude);\r\n");
      out.write(" \t});\r\n");
      out.write(" \t$(\".nanum_create\").click(function(){\r\n");
      out.write(" \t\t$(\"#create\").modal(\"hide\");  //추후에 spring연결과 함께 삭제\r\n");
      out.write(" \t});\r\n");
      out.write(" \t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl : \"jjam_3_boardlist.do\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t$(\".boardlist\").html(data);\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(data){\r\n");
      out.write("\t\t\talert(\"실패\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}); \t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------------------------상단 고정 메뉴바--------------------------------------------->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("   <h1 class=\"seperator\"></h1>\r\n");
      out.write("     <nav id=\"top_navcolor\" class=\"navbar fixed-top navbar navbar-expand-xl navbar-dark\">\r\n");
      out.write("         <!-- fixed-top 상단고정-->\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("             <!-- 브랜드 로고 삽입-->\r\n");
      out.write("             <a href=\"jjam_3_form.jsp\" class=\"navbar-brand\">\r\n");
      out.write("                 <img id=\"logo\" class=\"\" style=\"width: 60px; height: 60px;\" src=\"./resources/image/character.png\" alt=\"\"><img src=\"./resources/image/JJCR_white1.png\">\r\n");
      out.write("             </a>\r\n");
      out.write("             <!-- 햄버거 버튼-->\r\n");
      out.write("             <button class=\"navbar-toggler ham\" data-toggle=\"collapse\" data-target=\"#myNav\">\r\n");
      out.write("                 <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("             </button>\r\n");
      out.write("             <!-- 네비게이션 버튼 -->\r\n");
      out.write("             <div id=\"myNav\" class=\"collapse navbar-collapse justify-content-end\">\r\n");
      out.write("                 <ul class=\"navbar-nav\">\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">HOME</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_3_form.do\" class=\"nav-link\">나눔찾기(메인지도)</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_2_search.do\" class=\"nav-link\">검색하기</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_6_mypage.do\" class=\"nav-link\">마이페이지</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_login&out.do\" class=\"nav-link\">로그인/로그아웃</a>\r\n");
      out.write("                    \r\n");
      out.write("                     </li>\r\n");
      out.write("                 </ul>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </nav>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--------------------------------------본문 ------------------------------------------------------>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal-form\">\r\n");
      out.write("        <!--전체화면 분할-->\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("        <div class=\" modal-form-grid\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("            <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("      <!---------------------------------- 지도 api 자리-->\r\n");
      out.write("<!--             <div class=\"\"> -->\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"map_wrap\" >\r\n");
      out.write("    <div id=\"map\" class=\"map-custom\" ></div>\r\n");
      out.write("    <div class=\"hAddr\"  >\r\n");
      out.write("     </div><!--  end.hAddr -->\r\n");
      out.write("\t</div><!--  end div.map_wrap -->\r\n");
      out.write("     \r\n");
      out.write("<!--      <div id=\"map\" style=\"width:100px;height:350px;\"></div>       -->\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("<!--             </div>  그리드 맞춰줌-->\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        <!------------------------ 게시물  --------------------------->            \r\n");
      out.write("            <div class=\"boardlist\"></div> \r\n");
      out.write("       <!-- ------------------------------------------------------- -->\r\n");
      out.write("        <div style=\"text-align:center;\"><br><button class=\"btn btn-info create col-md-6\"  type=\"button\" data-toggle=\"modal\" data-target=\"#create\" >생성하기 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 안녕하세요</button></div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("           \r\n");
      out.write("        </div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("         <!--///  참여 생성 모달 예제////-->                            \r\n");
      out.write("        </div><!-- 그리드 왼쪽 공백-->\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div></div><div></div>\r\n");
      out.write("\r\n");
      out.write("            <!----------------------------------참여 MODAL창----------------------------------------->\r\n");
      out.write("\t<div id=\"jjoin\"></div>\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("            <!----------------------------------생성 MODAL창----------------------------------------->\r\n");
      out.write("\t<form action=\"insertBoard.do\" method=\"get\">\r\n");
      out.write("            <div id=\"create\" class=\"modal fade\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content modal-size\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h4>나눔 생성하기 </h4>\r\n");
      out.write("                     \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body \">\r\n");
      out.write("                            <div class=\"modal-inner-grid\">\r\n");
      out.write("                            <div class=\"form-group\"> <label for=\"\">회원 아이디 입력</label></div>\r\n");
      out.write("                                <div class=\"\"><input class=\"form-control\" type=\"text\"  name=\"c_id\"\r\n");
      out.write("                                        placeholder=\"아이디를 입력해주세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></div>\r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">무엇을 나누실 건가요?</label></div>\r\n");
      out.write("                                <div class=\"\"><input class=\"form-control\" type=\"text\" id=\"product\" name=\"b_name\"\r\n");
      out.write("                                        placeholder=\"물품을 입력해주세요\"> </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                   <div class=\"form-group\"> <label for=\"email\">카테고리를 선택해주세요</label></div>\r\n");
      out.write("                                <div class=\"\" style=\"text-align: right\">\r\n");
      out.write("                                <select id=\"icon\" name=\"cate_id\">\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/meat_pin.png\">육류</option> -->\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/vege_pin.png\">채소류</option> -->\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/spam_pin.png\">가공식품류</option> -->\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/seafood_pin.png\">어패류</option> -->\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/fruit_pin.png\">과일류</option> -->\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/bread_pin.png\">빵류</option> -->\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/spice_pin.png\">소스류</option> -->\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/nangdong_pin.png\">냉동식품류</option> -->\r\n");
      out.write("<!--                                         <option value=\"./resources/image/category_icons_pin/ingredients_pin.png\">기타등등</option> -->\r\n");
      out.write("                                        \r\n");
      out.write("                                        <option value=\"c0000\">육류</option>\r\n");
      out.write("                                        <option value=\"c0001\">채소류</option>\r\n");
      out.write("                                        <option value=\"c0002\">가공식품류</option>\r\n");
      out.write("                                        <option value=\"c0003\">어패류</option>\r\n");
      out.write("                                        <option value=\"c0004\">과일류</option>\r\n");
      out.write("                                        <option value=\"c0005\">빵류</option>\r\n");
      out.write("                                        <option value=\"c0006\">소스류</option>\r\n");
      out.write("                                        <option value=\"c0007\">냉동식품류</option>\r\n");
      out.write("                                        <option value=\"c0008\">기타등등</option>\r\n");
      out.write("                                    </select></div>\r\n");
      out.write("                                    \r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">몇개를 나누실 건가요?</label></div>\r\n");
      out.write("                                <div class=\"\" style=\"text-align: right\"><select name=\"b_ea\">\r\n");
      out.write("                                        <option value=\"1\">1</option>\r\n");
      out.write("                                        <option value=\"2\">2</option>\r\n");
      out.write("                                        <option value=\"3\">3</option>\r\n");
      out.write("                                        <option value=\"4\">4</option>\r\n");
      out.write("                                        <option value=\"5\">5</option>\r\n");
      out.write("                                        <option value=\"6\">6</option>\r\n");
      out.write("                                        <option value=\"7\">7</option>\r\n");
      out.write("                                        <option value=\"8\">8</option>\r\n");
      out.write("                                        <option value=\"9\">9</option>\r\n");
      out.write("                                    </select></div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- 위도경도값 히든처리 -->\r\n");
      out.write("                                <input type=\"hidden\" id=\"latitude\" name=\"b_latitude\" value=\"\"/>\r\n");
      out.write("                                <input type=\"hidden\" id=\"longitude\" name=\"b_longitude\" value=\"\"/>\r\n");
      out.write("                                   \r\n");
      out.write("                                 <div class=\"form-group\"> <label for=\"\" >나눔 위치를 확인해주세요</label></div>\r\n");
      out.write("                                <div class=\"\"><input class=\"form-control\" type=\"location\" id=\"location\"  name=\"b_location\" value=\"aaa\"> </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                   <div class=\"form-group\"> <label for=\"\" >게시글 제목을 입력해주세요</label></div>\r\n");
      out.write("                                <div class=\"\"><input class=\"form-control\" type=\"text\" id=\"\"  name=\"b_title\" value=\"aaa\"> </div> \r\n");
      out.write("                                       \r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">나눔 가격을 확인해주세요</label></div>\r\n");
      out.write("                                <div class=\"\"><input class=\"form-control\" type=\"price\" id=\"price\" name=\"b_price\" placeholder=\"0\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">언제까지 나눔할까요?</label></div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><input type=\"date\" class=\"col-sm-6\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> </div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><select>\r\n");
      out.write("                                            <option>for문 써서 24까지</option>\r\n");
      out.write("                                        </select><label>시</label></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                 <div class=\"form-group\"> <label for=\"\">게시글 내용을 적어주세요</label></div>\r\n");
      out.write("                                 <div class=\"\"><input class=\"form-control\" type=\"textarea\"  id=\"\" name=\"b_content\" placeholder=\"내용을 입력해주세요\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">나눔 물품의 사진을 올려주세요</label></div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><input type=\"button\" class=\"btn-dark col-sm-12\" value=\"이미지올리기\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> </div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><input type=\"submit\" class=\"col-sm-12 nanum_create\"\r\n");
      out.write("                                            style=\"color:white; background-color: #147b6b\" value=\"만들기\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> </div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><input type=\"button\" class=\"col-sm-12\"  data-dismiss=\"modal\"\r\n");
      out.write("                                            style=\"color:white; background-color: #f37f7f\" value=\"취소하기\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!------------------------------------------------------------------------->\r\n");
      out.write("            <!----------------------------------길찾기MODAL 창----------------------------------------->\r\n");
      out.write("\r\n");
      out.write("            <div id=\"road\" class=\"modal fade\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content modal-size\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h4>나눔까지 길찾기 </h4>\r\n");
      out.write("                      \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body \">\r\n");
      out.write("                            <div class=\"modal-inner-grid\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                                <li>(uesrId) 님의 나눔</li>\r\n");
      out.write("                                                <li>품목 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                                <li>위치 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                                <li>가격 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                                <li>날짜 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            여기에 가는길 출력\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                <!-- 맵위치 -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <input type=\"button\" class=\"col-sm-4\" style=\"color:white; background-color: #147b6b\"\r\n");
      out.write("                                value=\"참여하기\">\r\n");
      out.write("                            <input type=\"button\" class=\"col-sm-4\" style=\"color:white; background-color: #f37f7f\"\r\n");
      out.write("                                value=\"찜 하기\">\r\n");
      out.write("                            <input  data-dismiss=\"modal\" type=\"button\" class=\"col-sm-4\" style=\"color:white; background-color: #704242\"\r\n");
      out.write("                                value=\"더 둘러보기\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("                 <!-------------첫페이지 이미지 출력 modal----------------------------------------->\r\n");
      out.write("\r\n");
      out.write("                 <div id=\"info\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("                        <div class=\"modal-dialog modal-fullsize\" >\r\n");
      out.write("                            <div class=\"\"><!--css값 없음-->\r\n");
      out.write("                                    <div class=\"\"> </div>\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <div class=\"img-chatmodal\"></div>     \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!------------------------------------------------------------------------->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div></div> <!-- 그리드 오른쪽공백-->\r\n");
      out.write("        <!-- 그리드 아래 공백-->\r\n");
      out.write("        <div class=\"\"></div>\r\n");
      out.write("        <div></div>\r\n");
      out.write("        <div class=\"\"></div>\r\n");
      out.write("        <!------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- --------------------map api script------------------------------------------ -->\r\n");
      out.write("<!-- <script> -->\r\n");
      out.write("<!-- controller에서 가져온 값을 json으로 변환 -->\r\n");
      out.write("<!-- $(function(){ -->\r\n");
      out.write("\r\n");
      out.write("<!-- \tconsole.log(json); -->\r\n");
      out.write("<!-- \talert(json[0].b_date); -->\r\n");
      out.write("<!--  }); -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- </script> -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//map api\r\n");
      out.write("var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("    mapOption = { \r\n");
      out.write("        center: new kakao.maps.LatLng(37.54699, 127.09598), // 지도의 중심좌표\r\n");
      out.write("        level: 13 // 지도의 확대 레벨\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\r\n");
      out.write("//주소-좌표 변환 객체를 생성합니다\r\n");
      out.write("var geocoder = new kakao.maps.services.Geocoder();\r\n");
      out.write("\r\n");
      out.write("// 마커이미지의 주소입니다    \r\n");
      out.write("var imageSrc = \"http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_red.png\", \r\n");
      out.write("    imageSize = new kakao.maps.Size(64, 69), // 마커이미지의 크기입니다\r\n");
      out.write("    imageOption = {offset: new kakao.maps.Point(27, 69)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.\r\n");
      out.write("      \r\n");
      out.write("    var marker = new kakao.maps.Marker(); // 마커    \r\n");
      out.write("    \r\n");
      out.write(" var infowindow = new kakao.maps.InfoWindow({zindex:1}); //클릭한 위치에 대한 주소를 표시할 인포윈도우입니다\r\n");
      out.write("\r\n");
      out.write("    var markerImage = new kakao.maps.MarkerImage(\r\n");
      out.write("    \t    'http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_red.png',\r\n");
      out.write("    \t    new kakao.maps.Size(31, 35), new kakao.maps.Point(13, 34));\r\n");
      out.write(" \r\n");
      out.write(" // 현재 지도 중심좌표로 주소를 검색해서 지도 좌측 상단에 표시합니다\r\n");
      out.write("    searchAddrFromCoords(map.getCenter(), displayCenterInfo);\r\n");
      out.write(" \r\n");
      out.write("\t//위도,경도 변수선언\r\n");
      out.write(" \tvar latlng;\r\n");
      out.write("\tvar latitude;\r\n");
      out.write("\tvar longitude;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//화면 전환시 게시판리스트 변경\r\n");
      out.write("\tkakao.maps.event.addListener(map, 'bounds_changed', function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//지도 화면 전체의 위도 경도값 자르기\r\n");
      out.write("\t\tvar boundArr = new Array();\r\n");
      out.write("\t\tvar bounds = String(map.getBounds());\r\n");
      out.write("\t\tboundArr = bounds.split(',');\r\n");
      out.write("\t\tvar start_latitude = boundArr[0].substring(2,); //시작 위도\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar start_longitude2 = boundArr[1];\r\n");
      out.write("\t\tvar start_longitude1= start_longitude2.slice(0,-1);\r\n");
      out.write("\t\tvar start_longitude = start_longitude1.substring(1,);  // 시작 경도\r\n");
      out.write("\r\n");
      out.write("\t\tvar end_latitude1 = boundArr[2];\r\n");
      out.write("\t\tvar end_latitude= end_latitude1.substring(2,); // 끝 위도\r\n");
      out.write("\r\n");
      out.write("\t\tvar end_longitude2 = boundArr[3];\r\n");
      out.write("\t\tvar end_longitude1= end_longitude2.slice(0,-2);\r\n");
      out.write("\t\tvar end_longitude = end_longitude1.substring(1,); //끝 경도\r\n");
      out.write("\r\n");
      out.write("\t\t//위도 경도값 ajax로 전송\r\n");
      out.write("\t\t$(\".boardlist\").empty();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : \"jjam_3_changeboardlist.do\",\r\n");
      out.write("\t\t\tdata : \r\n");
      out.write("\t\t\t{ \t\"start_latitude\" : start_latitude,\r\n");
      out.write("\t\t\t\t\"start_longitude\" : start_longitude,\r\n");
      out.write("\t\t\t\t\"end_latitude\" : end_latitude,\r\n");
      out.write("\t\t\t\t\"end_longitude\" : end_longitude\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t$(\".boardlist\").html(data);\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(){\r\n");
      out.write("\t\t\t\talert(\"위도경도연결실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("//한번 클릭\r\n");
      out.write("    kakao.maps.event.addListener(map, 'click', function(mouseEvent) {\r\n");
      out.write("    \tsearchDetailAddrFromCoords(mouseEvent.latLng, function(result, status) {\t\r\n");
      out.write("\t\r\n");
      out.write("        latlng = mouseEvent.latLng;  //위도 경도값\r\n");
      out.write("        // 마커를 클릭한 위치에 표시합니다 \r\n");
      out.write("\t\tmarker.setPosition(mouseEvent.latLng);\r\n");
      out.write("        marker.setImage(markerImage);\r\n");
      out.write("        marker.setMap(map);\r\n");
      out.write("        \r\n");
      out.write("        if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("        \t var detailAddr = !!result[0].road_address ? '<div>도로명주소 : ' + result[0].road_address.address_name + '</div>' : '';\r\n");
      out.write("             detailAddr += '<div>지번 주소: ' +'<span class=\"address\">'+ result[0].address.address_name +'</span>'+ '</div>';\r\n");
      out.write("             \r\n");
      out.write("             //위도, 경도\r\n");
      out.write(" \t\tlatitude= latlng.getLat();\r\n");
      out.write("        longitude = latlng.getLng();\r\n");
      out.write("\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("             var content = '<div class=\"bAddr\">' +\r\n");
      out.write("                             '<span class=\"title\">법정동 주소정보</span>' +\r\n");
      out.write("                             detailAddr + '<span class=\"latitude\" style=\"display:none;\">'+latitude +'</span>' + '<span class=\"longitude\" style=\"display:none;\">'+longitude+'</span>'   //주소, 위도, 경도값\r\n");
      out.write("                         '</div>';\r\n");
      out.write("  \r\n");
      out.write("   // 인포윈도우에 클릭한 위치에 대한 법정동 상세 주소정보를 표시합니다\r\n");
      out.write("      infowindow.setContent(content);\r\n");
      out.write("      infowindow.open(map, marker);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write(" \r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("// db값 마커에 입력\r\n");
      out.write("\r\n");
      out.write("for(var i =0; i<jsonList.length; i++){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("marker = new kakao.maps.Marker({\r\n");
      out.write("\tmap: map,\r\n");
      out.write("    position: new kakao.maps.LatLng(jsonList[i].b_latitude, jsonList[i].b_longitude), \r\n");
      out.write("    image: new kakao.maps.MarkerImage(jsonList[i].cate_image, imageSize, imageOption) // 마커이미지 설정 \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// 마커에 표시할 인포윈도우를 생성합니다 \r\n");
      out.write("infowindow1 = new kakao.maps.InfoWindow({\r\n");
      out.write("    content:\r\n");
      out.write("    \t'<div class=\"wrap\">' + \r\n");
      out.write("        '    <div class=\"info\">' + \r\n");
      out.write("        '        <div class=\"title\" id=\"BTITLE\">' + \r\n");
      out.write("       \t\t\t\t jsonList[i].b_title + \r\n");
      out.write("        '        </div>' + \r\n");
      out.write("        '        <div class=\"body\">' + \r\n");
      out.write("        '            <div class=\"img\">' +\r\n");
      out.write("        '                <img src='+\"'\"+jsonList[i].cate_icon+\".png\"+\"'\"+'width=\"73\" height=\"70\">'+\r\n");
      out.write("        '           </div>'+ \r\n");
      out.write("        '            <div class=\"desc\">' + \r\n");
      out.write("        '                <span class=\"ellipsis\">내용 : </span><span id=\"BCONTENT\">'+jsonList[i].b_content+'</span></br>'+ \r\n");
      out.write("        '                <span class=\"jibun ellipsis\">가격 :'+'</span>'+'<span id=\"BPRICE\">'+jsonList[i].b_price+'</span></br>' + \r\n");
      out.write("        '                <div></div>' + \r\n");
      out.write("        '            </div>' + \r\n");
      out.write("        '        </div>' + \r\n");
      out.write("        '    </div>' +    \r\n");
      out.write("        '<span id=\"CID\" style=\"display:none;\">'+ jsonList[i].c_id+'</span></br>'+\r\n");
      out.write("        '<span id=\"BDATE\" style=\"display:none;\">'+jsonList[i].b_date+'</span></br>'+\r\n");
      out.write("        '<span id=\"BLOCATION\" style=\"display:none;\">'+jsonList[i].b_location+'</span></br>'+\r\n");
      out.write("        '<span id=\"BCATEICON\" style=\"display:none;\">'+jsonList[i].cate_icon+'</span></br>'+\r\n");
      out.write("        '<span id=\"CATENAME\" style=\"display:none;\">'+jsonList[i].cate_name+'</span></br>'+\r\n");
      out.write("        '<span id=\"BNO\" style=\"display:none;\">'+jsonList[i].b_no+'</span></br>'+\r\n");
      out.write("        '</div>'\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("'</div>'\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다\r\n");
      out.write("// 이벤트 리스너로는 클로저를 만들어 등록합니다 \r\n");
      out.write("// for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다\r\n");
      out.write("kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow1));\r\n");
      out.write("kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow1));\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//지도위 핀을 클릭했을때 모달에 연결\r\n");
      out.write("kakao.maps.event.addListener(marker, 'click', function(){\r\n");
      out.write("$(\"#jjoin\").empty();\r\n");
      out.write("//참여 모달창 연결\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\ttype:\"POST\",\r\n");
      out.write("\turl : \"jjam_3_participate.do\",\r\n");
      out.write("\tdata : \r\n");
      out.write("\t\t{\"b_title\" : $(\"#BTITLE\").text(),\r\n");
      out.write("\t\t \"c_id\" : $(\"#CID\").text(),\r\n");
      out.write("\t\t \"b_content\" : $(\"#BCONTENT\").text(),\r\n");
      out.write("\t\t \"b_price\" : $(\"#BPRICE\").text(),\r\n");
      out.write("\t\t \"b_location\" : $(\"#BLOCATION\").text(),\r\n");
      out.write("\t\t \"b_date\" : $(\"#BDATE\").text(),\r\n");
      out.write("\t\t \"cate_icon\" : $(\"#BCATEICON\").text(),\r\n");
      out.write("\t\t \"cate_name\": $(\"#CATENAME\").text(),\r\n");
      out.write("\t\t \"b_no\":$(\"#BNO\").text()\r\n");
      out.write("\t\t },\r\n");
      out.write("\r\n");
      out.write("\tsuccess: function(data){\r\n");
      out.write("\t\t$(\"#jjoin\").html(data);\r\n");
      out.write("\t\t$(\"#join\").modal(\"show\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t},\r\n");
      out.write("\terror: function(){\r\n");
      out.write("\t\talert(\"실패\")\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("//인포윈도우를 표시하는 클로저를 만드는 함수입니다 \r\n");
      out.write("function makeOverListener(map, marker, infowindow1) {\r\n");
      out.write("    return function() {\r\n");
      out.write("    \t\r\n");
      out.write("        infowindow1.open(map, marker);\r\n");
      out.write("    };\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 인포윈도우를 닫는 클로저를 만드는 함수입니다 \r\n");
      out.write("function makeOutListener(infowindow1) {\r\n");
      out.write("    return function() {\r\n");
      out.write("        infowindow1.close();\r\n");
      out.write("    };\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//중심 좌표나 확대 수준이 변경됐을 때 지도 중심 좌표에 대한 주소 정보를 표시하도록 이벤트를 등록합니다\r\n");
      out.write("kakao.maps.event.addListener(map, 'idle', function() {\r\n");
      out.write("    searchAddrFromCoords(map.getCenter(), displayCenterInfo);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function searchAddrFromCoords(coords, callback) {\r\n");
      out.write("    // 좌표로 행정동 주소 정보를 요청합니다\r\n");
      out.write("    geocoder.coord2RegionCode(coords.getLng(), coords.getLat(), callback);         \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function searchDetailAddrFromCoords(coords, callback) {\r\n");
      out.write("    // 좌표로 법정동 상세 주소 정보를 요청합니다\r\n");
      out.write("    geocoder.coord2Address(coords.getLng(), coords.getLat(), callback);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 지도 좌측상단에 지도 중심좌표에 대한 주소정보를 표출하는 함수입니다\r\n");
      out.write("function displayCenterInfo(result, status) {\r\n");
      out.write("    if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("        var infoDiv = document.getElementById('centerAddr');\r\n");
      out.write("\r\n");
      out.write("        for(var i = 0; i < result.length; i++) {\r\n");
      out.write("            // 행정동의 region_type 값은 'H' 이므로\r\n");
      out.write("//             if (result[i].region_type === 'H') {\r\n");
      out.write("//                 infoDiv.innerHTML = result[i].address_name;\r\n");
      out.write("//                 break;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }    \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--------------------------------  챗봇 api------------------- -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"frogue-container\" class=\"position-right-bottom\" data-chatbot=\"00b6f39a-b84c-48d4-9037-e20bfac8625a\" data-user=\"사용자ID\" data-init-key=\"value\"></div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        (function(d, s, id){\r\n");
      out.write("            var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("            if (d.getElementById(id)) {return;}\r\n");
      out.write("            js = d.createElement(s); js.id = id;\r\n");
      out.write("            js.src = \"https:\\/\\/danbee.ai/js/plugins/frogue-embed/frogue-embed.min.js\";\r\n");
      out.write("            fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("        }(document, 'script', 'frogue-embed'));\r\n");
      out.write("        </script> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
