/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-07-22 23:24:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jjam_005f2_005fsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1563837203950L));
    _jspx_dependants.put("/WEB-INF/views/chatbot.jsp", Long.valueOf(1563837203947L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/style/main.css\">\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/825d367943.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// 이미지 클릭 이벤트 \r\n");
      out.write("  \t$(\"input:image\").each(function(){\t\r\n");
      out.write("  \t\t\r\n");
      out.write("\t\t$(this).click(function(){\r\n");
      out.write("// \t\t$(\"#grid input[type='image']\").removeClass(\"selectImg\");\r\n");
      out.write("\t\t$(\"#grid input[type='image']\").css({\"background\":\"white\",\"border-radius\":\"0px\"});\r\n");
      out.write("\t\t$(this).css(\"border-radius:1px\");\r\n");
      out.write("\t\tvar idval= $(this).attr('id');\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\turl:\"boardByCate.do\",\r\n");
      out.write(" \t\t\tdata:{ \"cate_ename\" :idval },\r\n");
      out.write("\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t$(\".dong\").html(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(err){\r\n");
      out.write("\t\t\t\talert(\"연결실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t// 클릭한 이미지에 'selectImg' 추가 \r\n");
      out.write("// \t\t\t\t$(this).toggleClass('selectImg');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif($(this).hasClass('selectImg')){\r\n");
      out.write("\t\t\t\t// JSON LIST파싱\r\n");
      out.write("// \t\t\t\tvar jsonList = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jsonListCate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("// \t\t\t\tfor(var i=0; i<jsonListCate.length; i++){\t\t\r\n");
      out.write("// \t\t\t\t\t$('.card-columns').append(\"<div class='card w-100 \"\r\n");
      out.write("// \t\t\t\t\t\t\t+jsonListCate[i].cate_ename+\"'><img src=\"\r\n");
      out.write("// \t\t\t\t\t\t\t+\"'\"+jsonListCate[i].cate_icon+\".png' alt='' class='card-img-top'><div class='card-body'><h4 class='card-title'>\"\r\n");
      out.write("// \t\t\t\t\t\t\t+jsonListCate[i].c_id+\"님의 나눔</h4><div>\"\r\n");
      out.write("// \t\t\t\t\t\t\t+jsonListCate[i].b_name+\"/\"\r\n");
      out.write("// \t\t\t\t\t\t\t+jsonListCate[i].b_price+\"원/\"\r\n");
      out.write("// \t\t\t\t\t\t\t+jsonListCate[i].b_date+\"/\"\r\n");
      out.write("// \t\t\t\t\t\t\t+jsonListCate[i].b_location+\"/ \"\t\t\t\t\t\t\r\n");
      out.write("// \t\t\t\t\t\t\t+\"<input type='button' class='btn btn-success btn-sm' value='\"\r\n");
      out.write("// \t\t\t\t\t\t\t+\"참여하기\"\r\n");
      out.write("// \t\t\t\t\t\t\t+\"'></div></div></div>\");\r\n");
      out.write("// \t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//최초 클릭\r\n");
      out.write("// \t\t\t$('.selectImg').css({\"background\":\"white\",\"border-radius\":\"0px\"});\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t//클릭된 상태\r\n");
      out.write("\t\t\t$(this).removeAttr('style');\r\n");
      out.write("\t\t\t$('div[class*=\"'+idval+'\"]').remove();// 매퍼 변경 후 속성값을 jsonList[i].cate_ename 로 해주자 \r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t$(\".searchform\").click(function(){\r\n");
      out.write("\t\t$(\".dong\").empty();\r\n");
      out.write("\t\t\t$(\".searchform\").on(\"change keyup paste\", function(){   //키가 올라갈때마다 기존값을 변경시킴\r\n");
      out.write("\t\t\t\tvar currentVal = $(this).val();\r\n");
      out.write("\t\t\t\tvar queryString = $(\"form[name=testform]\").serialize();  //form값을 ajax로 보내기 위한 작업\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\turl : \"viewSearch.do\",\t\r\n");
      out.write("\t\t\t\t\tdata: queryString,\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t$(\".dong\").html(data);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},error: function(){\r\n");
      out.write("\t\t\t\t\t\talert(\"에러\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <!-- ---------------------------------상단 고정 메뉴바--------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <h1 class=\"seperator\"></h1>\r\n");
      out.write("     <nav id=\"top_navcolor\" class=\"navbar fixed-top navbar navbar-expand-xl navbar-dark\">\r\n");
      out.write("         <!-- fixed-top 상단고정-->\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("             <!-- 브랜드 로고 삽입-->\r\n");
      out.write("             <a href=\"jjam_3_form.jsp\" class=\"navbar-brand\">\r\n");
      out.write("                 <img id=\"logo\" class=\"\" style=\"width: 60px; height: 60px;\" src=\"./resources/image/character.png\" alt=\"\"><img src=\"./resources/image/JJCR_white1.png\">\r\n");
      out.write("             </a>\r\n");
      out.write("             <!-- 햄버거 버튼-->\r\n");
      out.write("             <button class=\"navbar-toggler ham\" data-toggle=\"collapse\" data-target=\"#myNav\">\r\n");
      out.write("                 <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("             </button>\r\n");
      out.write("             <!-- 네비게이션 버튼 -->\r\n");
      out.write("             <div id=\"myNav\" class=\"collapse navbar-collapse justify-content-end\">\r\n");
      out.write("                 <ul class=\"navbar-nav\">\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">HOME</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_3_form.do\" class=\"nav-link\">나눔찾기(메인지도)</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_2_search.do\" class=\"nav-link\">검색하기</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_6_mypage.do\" class=\"nav-link\">마이페이지</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"jjam_login&out.do\" class=\"nav-link\">로그인/로그아웃</a>\r\n");
      out.write("                    \r\n");
      out.write("                     </li>\r\n");
      out.write("                 </ul>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("<div class=\"search\"> <!--전체화면 분할-->\r\n");
      out.write("    <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("    <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("    <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("    \r\n");
      out.write("    <div></div><!-- 그리드 왼쪽 공백-->\r\n");
      out.write("    <div>\r\n");
      out.write("   \r\n");
      out.write("      <div id=\"grid\"> \r\n");
      out.write("      <!--  음식 카테고리 9개는 반복문으로 만듦  -->\r\n");
      out.write("      ");
 String ename[] = {"bread", "fruit", "ingredients", "meat", "nangdong", "seafood", "spam", "spice", "vege" }; 
      out.write("     \r\n");
      out.write("      ");
 for(int i=0; i<9; i++) {
      out.write("\r\n");
      out.write("        <div style=\"padding: 10px;\"><input type=\"image\" name=\"cate_ename\" \r\n");
      out.write("          id=\"");
      out.print(ename[i]);
      out.write("\" \r\n");
      out.write("          value=\"");
      out.print(ename[i]);
      out.write("\" \r\n");
      out.write("        src=\"./resources/image/category_icon/");
      out.print(ename[i]);
      out.write("_icon.png\" /></div>\r\n");
      out.write("      ");
}
      out.write("\r\n");
      out.write("           <!--  최근순, 근처, 인기순  -->   \r\n");
      out.write("             <div style=\"padding: 10px;\"><input type=\"image\"  src=\"./resources/image/category_icon/recent_icon.png\"/></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><input type=\"image\"  src=\"./resources/image/category_icon/nearby_icon.png\"/></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><input type=\"image\"  src=\"./resources/image/category_icon/hottem_icon.png\"/></div>\r\n");
      out.write("          </div>\r\n");
      out.write("                \r\n");
      out.write("    </div>\r\n");
      out.write("    <div></div>    <!-- 그리드 오른쪽공백-->  \r\n");
      out.write("     <!-- 그리드 아래 공백-->  \r\n");
      out.write("    <div class=\"\"></div>    \r\n");
      out.write("    <div></div>\r\n");
      out.write("    <div class=\"\"></div>   \r\n");
      out.write(" <!-------------검색창-------------->   \r\n");
      out.write("    <div class=\"\"></div>    \r\n");
      out.write("    <div>  \r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("        <form name=\"testform\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control searchform\" placeholder=\"검색어를 입력하세요\" name=\"b_title\"\r\n");
      out.write("            style=\"width :400%;\"> \r\n");
      out.write("          </form>\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("<!--                 <button class=\"btn btn-primary input-group-text\" type=\"button\"> -->\r\n");
      out.write("<!--                     <i class=\"fas fa-search\"></i> -->\r\n");
      out.write("<!--                 </button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("    <div class=\"\"></div>  \r\n");
      out.write("       <!-- 검색창 아래 공백-->  \r\n");
      out.write("       <div class=\"\"></div>    \r\n");
      out.write("       <div></div>\r\n");
      out.write("       <div class=\"\"></div> \r\n");
      out.write(" <!-------------게시글-------------->   \r\n");
      out.write(" <div class=\"\"></div>    \r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("        <!-- 동적으로 게시물을 받아와야함-->\r\n");
      out.write("        <div class=\"card-columns text-center dong\">\r\n");
      out.write("             <!-- 카드 1세트-->\r\n");
      out.write("             \r\n");
      out.write("        <!-------------- -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       </div>\r\n");
      out.write("            \r\n");
      out.write("        <!-- 게시글 끝 페이지 다운-->\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"\"></div> \r\n");
      out.write(" <div class=\"\"></div> \r\n");
      out.write(" <div class=\"\"></div> \r\n");
      out.write(" <div class=\"\"></div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--------------------------------  챗봇 api------------------- -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"frogue-container\" class=\"position-right-bottom\" data-chatbot=\"00b6f39a-b84c-48d4-9037-e20bfac8625a\" data-user=\"사용자ID\" data-init-key=\"value\"></div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        (function(d, s, id){\r\n");
      out.write("            var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("            if (d.getElementById(id)) {return;}\r\n");
      out.write("            js = d.createElement(s); js.id = id;\r\n");
      out.write("            js.src = \"https:\\/\\/danbee.ai/js/plugins/frogue-embed/frogue-embed.min.js\";\r\n");
      out.write("            fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("        }(document, 'script', 'frogue-embed'));\r\n");
      out.write("        </script> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 모달창 연결 -->\r\n");
      out.write("\t<div id=\"jjoin\"></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
