/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-07-16 01:21:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jjam_005f2_005fsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("        integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- https://getbootstrap.com/docs/4.3/getting-started/introduction/ 부트스트랩에서 가져옴-->\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/style/main.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/825d367943.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <!-- ---------------------------------상단 고정 메뉴바--------------------------------------------->\r\n");
      out.write("      <h1 class=\"seperator\"></h1>\r\n");
      out.write("      <nav id=\"top_navcolor\" class=\"navbar fixed-top navbar navbar-expand-xl navbar-dark\">\r\n");
      out.write("          <!-- fixed-top 상단고정-->\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("              <!-- 브랜드 로고 삽입-->\r\n");
      out.write("              <a href=\"JJAM_3_form.html\" class=\"navbar-brand\">\r\n");
      out.write("                  <img id=\"logo\" class=\"\" style=\"width: 60px; height: 60px;\" src=\"./resources/image/character.png\" alt=\"\"><img src=\"./resources/image/JJCR_white1.png\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <!-- 햄버거 버튼-->\r\n");
      out.write("              <button class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#myNav\">\r\n");
      out.write("                  <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("              </button>\r\n");
      out.write("              <!-- 네비게이션 버튼 -->\r\n");
      out.write("              <div id=\"myNav\" class=\"collapse navbar-collapse justify-content-end\">\r\n");
      out.write("                  <ul class=\"navbar-nav\">\r\n");
      out.write("                      <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">HOME</a></li>\r\n");
      out.write("                      <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">나눔찾기(메인지도)</a></li>\r\n");
      out.write("                      <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">검색하기</a></li>\r\n");
      out.write("                      <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">챗봇</a></li>\r\n");
      out.write("                      <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">로그인/로그아웃</a>\r\n");
      out.write("                     \r\n");
      out.write("                      </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("<div class=\"search\"> <!--전체화면 분할-->\r\n");
      out.write("    <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("    <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("    <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("    \r\n");
      out.write("    <div></div><!-- 그리드 왼쪽 공백-->\r\n");
      out.write("    <div>\r\n");
      out.write("   \r\n");
      out.write("      <div id=\"grid\">\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/bread_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/fruit_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/ingredients_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/meat_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/nangdong_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/seafood_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/spam_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/spice_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/vege_icon.png\" alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/recent_icon.png\"alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/nearby_icon.png\"alt=\"\"></div>\r\n");
      out.write("             <div style=\"padding: 10px;\"><img src=\"./resources/image/category_icon/hottem_icon.png\"alt=\"\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("                \r\n");
      out.write("    </div>\r\n");
      out.write("    <div></div>    <!-- 그리드 오른쪽공백-->  \r\n");
      out.write("     <!-- 그리드 아래 공백-->  \r\n");
      out.write("    <div class=\"\"></div>    \r\n");
      out.write("    <div></div>\r\n");
      out.write("    <div class=\"\"></div>   \r\n");
      out.write(" <!-------------검색창-------------->   \r\n");
      out.write("    <div class=\"\"></div>    \r\n");
      out.write("    <div>  \r\n");
      out.write("        <form action=\"/search/search\" method=\"GET\">\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"검색어를 입력하세요\">\r\n");
      out.write("            <div class=\"input-group-append\">\r\n");
      out.write("                <button class=\"btn btn-primary input-group-text\" type=\"submit\">\r\n");
      out.write("                    <i class=\"fas fa-search\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form></div>\r\n");
      out.write("    <div class=\"\"></div>  \r\n");
      out.write("       <!-- 검색창 아래 공백-->  \r\n");
      out.write("       <div class=\"\"></div>    \r\n");
      out.write("       <div></div>\r\n");
      out.write("       <div class=\"\"></div> \r\n");
      out.write(" <!-------------게시글-------------->   \r\n");
      out.write(" <div class=\"\"></div>    \r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("        <!-- 동적으로 게시물을 받아와야함-->\r\n");
      out.write("        <div class=\"card-columns text-center\">\r\n");
      out.write("            <!-- 카드 1세트-->\r\n");
      out.write("            <div class=\"card w-100\">\r\n");
      out.write("                <img src=\"./resources/image/apple.jpg\" alt=\"\" class=\"card-img-top\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title\" style=\"\">품목</h4>\r\n");
      out.write("                 <div>게시자 / 가격/ 개수/ 위치/ <input type=\"button\" class=\"btn btn-success btn-sm text-center\" value=\"참여하기\"></div>\r\n");
      out.write("             \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>         \r\n");
      out.write("        <!-------------- -->\r\n");
      out.write("          <!-- 카드 1세트-->\r\n");
      out.write("          <div class=\"card w-100\">\r\n");
      out.write("                <img src=\"./resources/image/pa.jpg\" alt=\"\" class=\"card-img-top\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title\">품목</h4>\r\n");
      out.write("                 <div>게시자 / 가격/ 개수/ 위치/ <input type=\"button\" class=\"btn btn-success btn-sm\" value=\"참여하기\"></div>\r\n");
      out.write("             \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>         \r\n");
      out.write("        <!-------------- -->\r\n");
      out.write("          <!-- 카드 1세트-->\r\n");
      out.write("          <div class=\"card w-100\">\r\n");
      out.write("                <img src=\"./resources/image/carrot.jpg\" alt=\"\" class=\"card-img-top\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h4 class=\"card-title\">품목</h4>\r\n");
      out.write("                 <div>게시자 / 가격/ 개수/ 위치/ <input type=\"button\" class=\"btn btn-success btn-sm\" value=\"참여하기\"></div>\r\n");
      out.write("             \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>         \r\n");
      out.write("        <!-------------- -->\r\n");
      out.write("       </div>\r\n");
      out.write("            \r\n");
      out.write("        <!-- 게시글 끝 페이지 다운-->\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"\"></div> \r\n");
      out.write(" <div class=\"\"></div> \r\n");
      out.write(" <div class=\"\"></div> \r\n");
      out.write(" <div class=\"\"></div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--------------------------------------------------------------------------->\r\n");
      out.write("<div class=\"footer fixed-bottom\">copylight</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
