/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-07-14 08:18:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jjam_005f3_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<!--     <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" -->\r\n");
      out.write("<!--         integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" -->\r\n");
      out.write("<!--         crossorigin=\"anonymous\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- https://getbootstrap.com/docs/4.3/getting-started/introduction/ 부트스트랩에서 가져옴-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=313dc2a3dad52079f42012b67c645f76&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/style/main.css\" >\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/825d367943.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("   \t $('#info').modal('show');// 페이지 진입시 레이어팝업 modal#info 실행\r\n");
      out.write("\t\r\n");
      out.write("   //map 관련 jquery문\r\n");
      out.write("     $(\".create\").click(function(){\r\n");
      out.write(" \t\tvar address = $(\".address\").text();\r\n");
      out.write(" \t\t$(\"#location\").prop('value',address);\r\n");
      out.write(" \t});\r\n");
      out.write(" \t$(\".nanum_create\").click(function(){\r\n");
      out.write(" \t\talert(\"나눔생성\");\r\n");
      out.write(" \t\tvar a= $(\"#icon option:selected\").val();\r\n");
      out.write(" \t\tnew kakao.maps.Marker({\r\n");
      out.write(" \t\t    position: new kakao.maps.LatLng(latitude, longitude), \r\n");
      out.write(" \t\t    image: new kakao.maps.MarkerImage(a, imageSize, imageOption) // 마커이미지 설정 \r\n");
      out.write(" \t\t}).setMap(map);  \r\n");
      out.write(" \t\t$(\"#create\").modal(\"hide\");  //추후에 spring연결과 함께 삭제\r\n");
      out.write(" \t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------------------------상단 고정 메뉴바--------------------------------------------->\r\n");
      out.write("     <h1 class=\"seperator\"></h1>\r\n");
      out.write("     <nav id=\"top_navcolor\" class=\"navbar fixed-top navbar navbar-expand-xl navbar-dark\">\r\n");
      out.write("         <!-- fixed-top 상단고정-->\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("             <!-- 브랜드 로고 삽입-->\r\n");
      out.write("             <a href=\"jjam_3_form.jsp\" class=\"navbar-brand\">\r\n");
      out.write("                 <img id=\"logo\" class=\"\" style=\"width: 60px; height: 60px;\" src=\"./resources/image/character.png\" alt=\"\"><img src=\"./resources/image/JJCR_white1.png\">\r\n");
      out.write("             </a>\r\n");
      out.write("             <!-- 햄버거 버튼-->\r\n");
      out.write("             <button class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#myNav\">\r\n");
      out.write("                 <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("             </button>\r\n");
      out.write("             <!-- 네비게이션 버튼 -->\r\n");
      out.write("             <div id=\"myNav\" class=\"collapse navbar-collapse justify-content-end\">\r\n");
      out.write("                 <ul class=\"navbar-nav\">\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">HOME</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">나눔찾기(메인지도)</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">검색하기</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">챗봇</a></li>\r\n");
      out.write("                     <li class=\"nav-item\"><a href=\"\" class=\"nav-link\">로그인/로그아웃</a>\r\n");
      out.write("                    \r\n");
      out.write("                     </li>\r\n");
      out.write("                 </ul>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </nav>\r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("    <!--------------------------------------본문 ------------------------------------------------------>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal-form\">\r\n");
      out.write("        <!--전체화면 분할-->\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("        <div class=\" modal-form-grid\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("            <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("      <!---------------------------------- 지도 api 자리-->\r\n");
      out.write("<!--             <div class=\"\"> -->\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"map_wrap\">\r\n");
      out.write("    <div id=\"map\" class=\"map-custom\" ></div>\r\n");
      out.write("    <div class=\"hAddr\">\r\n");
      out.write("     </div><!--  end.hAddr -->\r\n");
      out.write("\t</div><!--  end div.map_wrap -->\r\n");
      out.write("     \r\n");
      out.write("<!--      <div id=\"map\" style=\"width:100px;height:350px;\"></div>       -->\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("<!--             </div>  그리드 맞춰줌-->\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <!-- 게시물  -->            \r\n");
      out.write("            <div class=\"\">\r\n");
      out.write("                <div class=\"form-list\" style=\" text-align: center\">\r\n");
      out.write("                   <div></div> <div><img class=\"w-100\" src=\"./resources/image/category_icon/fruit_icon.png\" alt=\"\"></div><div></div><div class=\"btn-light\" style=\"border-radius: 50px; margin:  3px;\">\r\n");
      out.write("                    <a href=\"\" data-toggle=\"modal\"  data-target=\"#join\">참여하기</a></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <!------------------------------------------------------------------------------->\r\n");
      out.write("                   <div></div> <div><img class=\"w-100\" src=\"./resources/image/category_icon/fruit_icon.png\"  alt=\"\"></div><div></div><div class=\"btn-light\" style=\"border-radius: 50px; margin:  3px;\">\r\n");
      out.write("                    <a href=\"\" data-toggle=\"modal\" data-target=\"#join\">참여하기</a></div>\r\n");
      out.write("                   \r\n");
      out.write("                   <div></div> <div><img class=\"w-100\" src=\"./resources/image/category_icon/fruit_icon.png\"  alt=\"\"></div><div></div><div class=\"btn-light\" style=\"border-radius: 50px; margin:  3px;\">\r\n");
      out.write("                    <a href=\"\" data-toggle=\"modal\" data-target=\"#join\">참여하기</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> \r\n");
      out.write("        \r\n");
      out.write("            <!--///  참여 생성 모달 예제////-->                            \r\n");
      out.write("                <a href=\"\"  data-toggle=\"modal\" data-target=\"#create\" class=\"create\">생성하기</a>\r\n");
      out.write("\r\n");
      out.write("        </div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"\"></div> <!-- 상단 navbar로 인한 공백-->\r\n");
      out.write("\r\n");
      out.write("        <div></div><!-- 그리드 왼쪽 공백-->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("            <!----------------------------------참여 MODAL창----------------------------------------->\r\n");
      out.write("\r\n");
      out.write("            <div id=\"join\" class=\"modal fade\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content modal-size\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h4>나눔에 참여하기 </h4>\r\n");
      out.write("                         \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body \">\r\n");
      out.write("                            <div class=\"modal-inner-grid\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                            <li>(uesrId) 님의 나눔</li>\r\n");
      out.write("                                            <li>품목 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                            <li>위치 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                            <li>가격 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                            <li>날짜 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-12\"\r\n");
      out.write("                                        style=\"display: grid; grid-template-columns:50% 50%; grid-template-rows:50% 50%;\">\r\n");
      out.write("                                        <input type=\"button\" class=\"col-sm-12\"\r\n");
      out.write("                                            style=\"color:white; background-color: #147b6b\" value=\"참여하기\" data-toggle=\"modal\" data-target=\"#pay\">\r\n");
      out.write("                                        <input type=\"button\" class=\"col-sm-12\"\r\n");
      out.write("                                            style=\"color:white; background-color: #f37f7f\" value=\"찜 하기\">\r\n");
      out.write("                                        <input type=\"button\" class=\"col-sm-12\"  data-dismiss=\"modal\"\r\n");
      out.write("                                            style=\"color:white; background-color: #999999\" value=\"취소\">\r\n");
      out.write("                                        <input type=\"button\" class=\"col-sm-12\"\r\n");
      out.write("                                            style=\"color:white; background-color: #558ccf\" value=\"길찾기\"\r\n");
      out.write("                                            data-toggle=\"modal\" data-target=\"#road\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div><img src=\"./resources/image/apple.jpg\" class=\"w-100 h-100\" alt=\"\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!----------------------------------생성 MODAL창----------------------------------------->\r\n");
      out.write("\r\n");
      out.write("            <div id=\"create\" class=\"modal fade\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content modal-size\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h4>나눔 생성하기 </h4>\r\n");
      out.write("                     \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body \">\r\n");
      out.write("                            <div class=\"modal-inner-grid\">\r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">무엇을 나누실 건가요?</label></div>\r\n");
      out.write("                                <div class=\"\"><input class=\"form-control\" type=\"product\" id=\"product\"\r\n");
      out.write("                                        placeholder=\"물품을 입력해주세요\"> </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                   <div class=\"form-group\"> <label for=\"email\">카테고리를 선택해주세요</label></div>\r\n");
      out.write("                                <div class=\"\" style=\"text-align: right\">\r\n");
      out.write("                                <select id=\"icon\">\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/meat_pin.png\">육류</option>\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/vege_pin.png\">채소류</option>\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/spam_pin.png\">가공식품류</option>\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/seafood_pin.png\">어패류</option>\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/fruit_pin.png\">과일류</option>\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/bread_pin.png\">빵류</option>\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/spice_pin.png\">소스류</option>\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/nangdong_pin.png\">냉동식품류</option>\r\n");
      out.write("                                        <option value=\"./resources/image/category_icons_pin/ingredients_pin.png\">기타등등</option>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </select></div>\r\n");
      out.write("                                    \r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">몇명에게 나누실 건가요?</label></div>\r\n");
      out.write("                                <div class=\"\" style=\"text-align: right\"><select>\r\n");
      out.write("                                        <option value=\"1\">1</option>\r\n");
      out.write("                                        <option value=\"2\">2</option>\r\n");
      out.write("                                        <option value=\"3\">3</option>\r\n");
      out.write("                                        <option value=\"4\">4</option>\r\n");
      out.write("                                    </select></div>\r\n");
      out.write("                                    \r\n");
      out.write("                                 <div class=\"form-group\"> <label for=\"email\" >나눔 위치를 확인해주세요</label></div>\r\n");
      out.write("                                <div class=\"\"><input class=\"form-control\" type=\"location\" id=\"location\" value=\"aaa\"> </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">나눔 가격을 확인해주세요</label></div>\r\n");
      out.write("                                <div class=\"\"><input class=\"form-control\" type=\"price\" id=\"price\" placeholder=\"0\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">언제까지 나눔할까요?</label></div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><input type=\"date\" class=\"col-sm-6\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> </div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><select>\r\n");
      out.write("                                            <option>for문 써서 24까지</option>\r\n");
      out.write("                                        </select><label>시</label></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> <label for=\"email\">나눔 물품의 사진을 올려주세요</label></div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><input type=\"button\" class=\"btn-dark col-sm-12\" value=\"이미지올리기\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> </div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><input type=\"button\" class=\"col-sm-12 nanum_create\"\r\n");
      out.write("                                            style=\"color:white; background-color: #147b6b\" value=\"만들기\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\"> </div>\r\n");
      out.write("                                <div class=\"\">\r\n");
      out.write("                                    <div><input type=\"button\" class=\"col-sm-12\"  data-dismiss=\"modal\"\r\n");
      out.write("                                            style=\"color:white; background-color: #f37f7f\" value=\"취소하기\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!------------------------------------------------------------------------->\r\n");
      out.write("            <!----------------------------------길찾기MODAL 창----------------------------------------->\r\n");
      out.write("\r\n");
      out.write("            <div id=\"road\" class=\"modal fade\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content modal-size\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h4>나눔까지 길찾기 </h4>\r\n");
      out.write("                      \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body \">\r\n");
      out.write("                            <div class=\"modal-inner-grid\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                                <li>(uesrId) 님의 나눔</li>\r\n");
      out.write("                                                <li>품목 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                                <li>위치 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                                <li>가격 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                                <li>날짜 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            여기에 가는길 출력\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                <!-- 맵위치 -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <input type=\"button\" class=\"col-sm-4\" style=\"color:white; background-color: #147b6b\"\r\n");
      out.write("                                value=\"참여하기\">\r\n");
      out.write("                            <input type=\"button\" class=\"col-sm-4\" style=\"color:white; background-color: #f37f7f\"\r\n");
      out.write("                                value=\"찜 하기\">\r\n");
      out.write("                            <input  data-dismiss=\"modal\" type=\"button\" class=\"col-sm-4\" style=\"color:white; background-color: #704242\"\r\n");
      out.write("                                value=\"더 둘러보기\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!----------------------------------참여 MODAL창----------------------------------------->\r\n");
      out.write("\r\n");
      out.write("            <div id=\"pay\" class=\"modal fade\">\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content modal-size\">\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h4>결제 </h4>\r\n");
      out.write("                             \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <div >\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <li>(uesrId) 님의 나눔</li>\r\n");
      out.write("                                            <li>품목 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                            <li>위치 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                            <li>가격 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("                                            <li>날짜 &nbsp; : 디비에서 가져온 값</li>\r\n");
      out.write("\r\n");
      out.write("                                            <li><input type=\"checkbox\" class=\"checkbox\"> 위의 내용을 확인 하셨습니까?</li>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"col-lg-12\"\r\n");
      out.write("                                            style=\"display: grid;  grid-template-rows:50% 50%;\">\r\n");
      out.write("                                            <input type=\"button\" class=\"col-sm-12\" style=\"border-radius: 10px; color:white; background-color: #d4b113\" value=\"카카오페이\">\r\n");
      out.write("                                            <input  data-dismiss=\"modal\" type=\"button\" class=\"col-sm-12\" style=\"border-radius: 10px; color:white; background-color: #525252\" value=\"돌아가기\">\r\n");
      out.write("                                         \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                 \r\n");
      out.write("                                </div>\r\n");
      out.write("    \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-footer\">\r\n");
      out.write("    \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                 <!----------------------------------챗봇 modal info----------------------------------------->\r\n");
      out.write("\r\n");
      out.write("                 <div id=\"info\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("                        <div class=\"modal-dialog modal-fullsize\" >\r\n");
      out.write("                            <div class=\"\"><!--css값 없음-->\r\n");
      out.write("                                    <div class=\"\"> </div>\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <div class=\"img-chatmodal\"></div>     \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!------------------------------------------------------------------------->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div></div> <!-- 그리드 오른쪽공백-->\r\n");
      out.write("        <!-- 그리드 아래 공백-->\r\n");
      out.write("        <div class=\"\"></div>\r\n");
      out.write("        <div></div>\r\n");
      out.write("        <div class=\"\"></div>\r\n");
      out.write("        <!------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- --------------------map api script------------------------------------------ -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("    mapOption = { \r\n");
      out.write("        center: new kakao.maps.LatLng(37.54699, 127.09598), // 지도의 중심좌표\r\n");
      out.write("        level: 13 // 지도의 확대 레벨\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\r\n");
      out.write("//주소-좌표 변환 객체를 생성합니다\r\n");
      out.write("var geocoder = new kakao.maps.services.Geocoder();\r\n");
      out.write("\r\n");
      out.write("// 마커이미지의 주소입니다    \r\n");
      out.write("var imageSrc = \"http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_red.png\", \r\n");
      out.write("    imageSize = new kakao.maps.Size(64, 69), // 마커이미지의 크기입니다\r\n");
      out.write("    imageOption = {offset: new kakao.maps.Point(27, 69)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.\r\n");
      out.write("      \r\n");
      out.write("    var marker = new kakao.maps.Marker(); // 마커    \r\n");
      out.write("    \r\n");
      out.write(" var infowindow = new kakao.maps.InfoWindow({zindex:1}); //클릭한 위치에 대한 주소를 표시할 인포윈도우입니다\r\n");
      out.write("\r\n");
      out.write("    var markerImage = new kakao.maps.MarkerImage(\r\n");
      out.write("    \t    'http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_red.png',\r\n");
      out.write("    \t    new kakao.maps.Size(31, 35), new kakao.maps.Point(13, 34));\r\n");
      out.write(" \r\n");
      out.write(" // 현재 지도 중심좌표로 주소를 검색해서 지도 좌측 상단에 표시합니다\r\n");
      out.write("    searchAddrFromCoords(map.getCenter(), displayCenterInfo);\r\n");
      out.write(" \r\n");
      out.write("\t//위도,경도 변수선언\r\n");
      out.write(" \tvar latlng;\r\n");
      out.write("\tvar latitude;\r\n");
      out.write("\tvar longitude;\r\n");
      out.write("//한번 클릭\r\n");
      out.write("    kakao.maps.event.addListener(map, 'click', function(mouseEvent) {\r\n");
      out.write("    \tsearchDetailAddrFromCoords(mouseEvent.latLng, function(result, status) {\r\n");
      out.write("    \t\t\r\n");
      out.write("        latlng = mouseEvent.latLng;  //위도 경도값\r\n");
      out.write("        // 마커를 클릭한 위치에 표시합니다 \r\n");
      out.write("\t\tmarker.setPosition(mouseEvent.latLng);\r\n");
      out.write("        marker.setImage(markerImage);\r\n");
      out.write("        marker.setMap(map);\r\n");
      out.write("        \r\n");
      out.write("        if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("        \t var detailAddr = !!result[0].road_address ? '<div>도로명주소 : ' + result[0].road_address.address_name + '</div>' : '';\r\n");
      out.write("             detailAddr += '<div>지번 주소: ' +'<span class=\"address\">'+ result[0].address.address_name +'</span>'+ '</div>';\r\n");
      out.write("             \r\n");
      out.write("             //위도, 경도\r\n");
      out.write("             var a = String(latlng);\r\n");
      out.write("             latitude = String(a.substring(1,18));\r\n");
      out.write("             longitude = String(a.substring(20,38));\r\n");
      out.write("             \r\n");
      out.write("             var content = '<div class=\"bAddr\">' +\r\n");
      out.write("                             '<span class=\"title\">법정동 주소정보</span>' + \r\n");
      out.write("                             detailAddr + latlng +   //주소, 위도, 경도값\r\n");
      out.write("                         '</div>';\r\n");
      out.write("  \r\n");
      out.write("   // 인포윈도우에 클릭한 위치에 대한 법정동 상세 주소정보를 표시합니다\r\n");
      out.write("      infowindow.setContent(content);\r\n");
      out.write("      infowindow.open(map, marker);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write(" \r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    });\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("new kakao.maps.Marker({\r\n");
      out.write("    position: new kakao.maps.LatLng(37.43699, 127.09598), \r\n");
      out.write("    image: new kakao.maps.MarkerImage(\"./resources/image/category_icons_pin/meat_pin.png\", imageSize, imageOption) // 마커이미지 설정 \r\n");
      out.write("}).setMap(map);  \r\n");
      out.write("new kakao.maps.Marker({\r\n");
      out.write("    position: new kakao.maps.LatLng(36.54699, 127.09598), \r\n");
      out.write("    image: new kakao.maps.MarkerImage(\"./resources/image/category_icons_pin/ingredients_pin.png\", imageSize, imageOption) // 마커이미지 설정 \r\n");
      out.write("}).setMap(map);  \r\n");
      out.write("new kakao.maps.Marker({\r\n");
      out.write("    position: new kakao.maps.LatLng(36.24699, 127.09598), \r\n");
      out.write("    image: new kakao.maps.MarkerImage(\"./resources/image/category_icons_pin/seafood_pin.png\", imageSize, imageOption) // 마커이미지 설정 \r\n");
      out.write("}).setMap(map);  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//중심 좌표나 확대 수준이 변경됐을 때 지도 중심 좌표에 대한 주소 정보를 표시하도록 이벤트를 등록합니다\r\n");
      out.write("kakao.maps.event.addListener(map, 'idle', function() {\r\n");
      out.write("    searchAddrFromCoords(map.getCenter(), displayCenterInfo);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function searchAddrFromCoords(coords, callback) {\r\n");
      out.write("    // 좌표로 행정동 주소 정보를 요청합니다\r\n");
      out.write("    geocoder.coord2RegionCode(coords.getLng(), coords.getLat(), callback);         \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function searchDetailAddrFromCoords(coords, callback) {\r\n");
      out.write("    // 좌표로 법정동 상세 주소 정보를 요청합니다\r\n");
      out.write("    geocoder.coord2Address(coords.getLng(), coords.getLat(), callback);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 지도 좌측상단에 지도 중심좌표에 대한 주소정보를 표출하는 함수입니다\r\n");
      out.write("function displayCenterInfo(result, status) {\r\n");
      out.write("    if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("        var infoDiv = document.getElementById('centerAddr');\r\n");
      out.write("\r\n");
      out.write("        for(var i = 0; i < result.length; i++) {\r\n");
      out.write("            // 행정동의 region_type 값은 'H' 이므로\r\n");
      out.write("//             if (result[i].region_type === 'H') {\r\n");
      out.write("//                 infoDiv.innerHTML = result[i].address_name;\r\n");
      out.write("//                 break;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }    \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--------------------------------  챗봇 api------------------- -->\r\n");
      out.write(" <div id=\"frogue-container\" class=\"position-right-bottom\" data-chatbot=\"00b6f39a-b84c-48d4-9037-e20bfac8625a\" data-user=\"사용자ID\" data-init-key=\"value\"></div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        (function(d, s, id){\r\n");
      out.write("            var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("            if (d.getElementById(id)) {return;}\r\n");
      out.write("            js = d.createElement(s); js.id = id;\r\n");
      out.write("            js.src = \"https:\\/\\/danbee.ai/js/plugins/frogue-embed/frogue-embed.min.js\";\r\n");
      out.write("            fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("        }(document, 'script', 'frogue-embed'));\r\n");
      out.write("        </script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
